### ISSUE TITLE
taste-tester logging crash: undefined local variable or method 'logger' for #<TasteTester::State>

### ISSUE THREAD

**Issue by rb2k** [facebook/taste-tester#156]
I just ran into this stacktrace when testing on macOS

I thought I'd report it since we should probably never end up in this "undefined local variable or method" situation:

```
DEBUG: Executing: USER=kickstart /opt/chefdk/embedded/bin/taste-tester test -vv -m server.x.y.com:5376 --transport locallink --linkonly --really -s localhost -y -p /opt/facebook/ops/scripts/chef/taste-tester-hooks.rb -t 1d
DEBUG: ERR: /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/taste_tester-0.0.13/lib/taste_tester/state.rb:39:in `rescue in initialize':
DEBUG: ERR: undefined local variable or method `logger' for #<TasteTester::State:0x00007f9589b20658> (NameError)
DEBUG: ERR: Did you mean?  @@logger
DEBUG: ERR:  from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/taste_tester-0.0.13/lib/taste_tester/state.rb:36:in `initialize'
DEBUG: ERR:  from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/taste_tester-0.0.13/lib/taste_tester/server.rb:36:in `new'
DEBUG: ERR:  from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/taste_tester-0.0.13/lib/taste_tester/server.rb:36:in `initialize'
DEBUG: ERR:  from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/taste_tester-0.0.13/lib/taste_tester/commands.rb:80:in `new'
DEBUG: ERR:  from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/taste_tester-0.0.13/lib/taste_tester/commands.rb:80:in `test'
DEBUG: ERR:  from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/taste_tester-0.0.13/bin/taste-tester:400:in `<module:TasteTester>'
DEBUG: ERR:  from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/taste_tester-0.0.13/bin/taste-tester:32:in `<top (required)>'
DEBUG: ERR:  from /opt/chefdk/embedded/bin/taste-tester:23:in `load'
DEBUG: ERR:  from /opt/chefdk/embedded/bin/taste-tester:23:in `<main>'
DEBUG: OUT: Loading plugin at /opt/facebook/ops/scripts/chef/taste-tester-hooks.rb
DEBUG: OUT: Skipping upload at user request... potentially dangerous!
```

**Comment by jaymzh** [comment]
You're on an ancient version. I'm fairly certain that was fixed quite a while ago. Please try on 0.0.19 and report again if it's still an issue.
